### PR TITLE
Fix automatic event fill in newsletter

### LINKED ISSUE #1315: Event information is not automatically filled in in newsletter
### Describe the bug
When making the newsletter and selecting the events to show it doesn't automatically fill in all the information about an event when you select one.

### How to reproduce
Steps to reproduce the behaviour:
1. Make a new newsletter
2. Click on 'Add another newsletter event'
3. Select an event in the dropdown menu
4. See that it doesn't fill everything in automatically

### Expected behaviour
It fills in the information about the event automatically

### Screenshots
image

### PR DESCRIPTION
**Pull request by Jorritboer**
Closes #1315 

### Summary
The newsletter now fills in the events automatically again.

### How to test
Steps to test the changes you made:
1. Create a new newsletter
2. Click on 'Add newsletter event'
3. Select an event in the dropdown menu

### CODE REVIEW

File: website/newsletters/static/admin/newsletters/js/forms.js [hunk 1]
```diff
@@ -79,25 +79,12 @@ django.jQuery(function () {
     }
 
     function getEvent(pk, success) {
-        var originalLang = $('html').attr('lang');
-        switchLanguage('nl', function () {
```
Comment (pingiun) [inline website/newsletters/static/admin/newsletters/js/forms.js:83]: This old switchLanguage function can now be deleted

**Review by pingiun — CHANGES_REQUESTED** [review]

**Review by pingiun — APPROVED** [review]
